import json, os
CATS = ["Numbers, time and data", "Reading, writing and words", "Art, music and making", "Science and nature", "Puzzles and strategy games", "Coding and computing", "World and culture", "Tools and sharing"]
# name: (category, age, needs, description)
D = {
"Abacus": (0, "5+ with an adult", "", "Move beads on a counting frame and watch the number build up (\"20 + 3 = 23\"). An adult should choose the Decimal type and 3 rods first."),
"Sprint Math": (0, "6+", "", "Answer as many mental arithmetic questions as you can before the time runs out."),
"Tank Operation": (0, "6+", "", "An arcade game to practise math facts, with several levels of difficulty."),
"Fraction": (0, "7+", "", "Nudge a bouncing ball so it lands on the fraction or percentage shown on it."),
"Calculate": (0, "8+", "", "A calculator that also handles formulas, variables and simple graphs."),
"MindMath": (0, "9+", "", "Reach a target number from five given numbers using + − × ÷, like the Countdown numbers round."),
"Clock Web": (0, "5+", "", "Learn to read and tell the time on an analog and a digital clock."),
"Stopwatch": (0, "6+", "", "Several independent digital stopwatches for timing things."),
"Chart": (0, "8+", "", "Type in data and turn it into bar, pie or line charts."),
"3D Volume": (0, "7+", "", "Pick a 3D solid (cube, tetrahedron, octahedron, dodecahedron, icosahedron), color it and explore its volume."),
"Abecedarium": (1, "3+", "", "Learn the alphabet with pictures, sounds and words."),
"Calligra": (1, "4+", "", "Practise cursive handwriting of letters and numbers."),
"Speak": (1, "4+", "", "A talking face that reads out loud whatever you type."),
"Story": (1, "6+", "", "Pictures prompt you to write a story that ties them together."),
"Write": (1, "6+", "", "A simple word processor for children: format text, change colors and add images."),
"Falabracman": (1, "7+", "", "A maze game where you collect the letters of a target word in order, without falling into ponds."),
"Ebook Reader": (1, "6+", "Internet for the library", "Read electronic books in ePub format from a library."),
"Markdown": (1, "10+", "", "Write in Markdown and see the formatted text beside it."),
"Paint": (2, "4+", "", "Draw with pens, stamps, text and colors, fill areas, copy and paste, and save to the Journal."),
"Grid Paint": (2, "4+", "", "Color a grid of triangles to make patterns and pictures."),
"XO Editor": (2, "3+", "", "Choose the colors of your own buddy icon."),
"Xmas Lights": (2, "4+", "", "Make blinking Christmas-light displays from Sugarizer icons and colors."),
"FotoToon": (2, "7+", "", "Make a comic strip from your pictures, drawings and images in a few minutes."),
"Stickman": (2, "7+", "", "Pose a stick figure frame by frame to make an animation."),
"Record": (2, "5+", "A camera and microphone", "Capture photos, video and sound."),
"TamTam Micro": (2, "4+", "", "Play many kinds of instruments, sounds and noises."),
"Planets": (3, "5+", "", "Explore 3D models of the planets."),
"Moon": (3, "7+", "", "See the current phase of the Moon, with information on the next phases and eclipses."),
"Constellation": (3, "8+", "", "An offline planetarium showing what is visible in the sky from any place on Earth."),
"Human Body": (3, "7+", "", "Explore the human body in 3D with layers, highlight parts and play a quiz."),
"FoodChain": (3, "5+", "", "Learn animal names and how to say them, and discover who eats whom in a food chain."),
"Physics JS": (3, "6+", "", "Drop circles, boxes and triangles into a world with gravity and watch them move and collide."),
"Gears": (3, "7+", "", "Build chains of gears and watch them turn together."),
"Measure": (3, "9+", "A microphone", "Learn how sound works by viewing sound signals as they happen."),
"Tangram": (4, "5+", "", "Rebuild animals and objects from the seven classic tangram pieces."),
"Memorize": (4, "4+", "", "Find matching pairs of cards (numbers, letters, sounds), or make your own game."),
"Maze Web": (4, "5+", "", "Guide the red smiley through mazes that get bigger at each level."),
"Flip": (4, "6+", "", "Flip discs until they are all the same color; each win makes the next one harder."),
"Reflection": (4, "6+", "", "Learn mirror symmetry by reproducing a pattern on the other side of a line."),
"Implode": (4, "7+", "", "Remove groups of three or more same-colored blocks until none are left."),
"Blockrain": (4, "7+", "", "A tile-matching game of falling blocks, inspired by Tetris."),
"Chess": (4, "6+", "", "Play chess against the computer or a friend; hovering a piece shows its legal moves."),
"Last One Loses": (4, "6+", "", "Take items in turn and avoid taking the last one, against the computer or another player."),
"Turtle Blocks JS": (5, "8+", "", "Snap blocks together to make a turtle draw colorful art: an easy first step into programming."),
"Scratch": (5, "7+", "", "Scratch 3.0 visual programming: build stories, games and animations from blocks."),
"Etoys": (5, "8+", "", "Build interactive projects and simulations by dragging scripts (Squeak Etoys)."),
"Jappy": (5, "10+", "", "Write and run programs in a Python-like language."),
"Game Of Life": (5, "9+", "", "Watch cells live, die and multiply by simple rules, from a pattern, at random or your own."),
"QRCode": (5, "8+", "", "Create and read QR codes."),
"Color My World": (6, "5+", "", "Color the countries of a world map, play a geography game and take a virtual tour."),
"Dollar Street": (6, "8+", "Internet", "Browse photos of homes and everyday things from families around the world, filtered by income."),
"Video Viewer": (6, "8+", "Internet", "Browse and watch educational videos from Khan Academy, Canopé and more."),
"Chat": (7, "7+", "A Sugarizer Server", "Chat with other users on the same network."),
"Shared Notes": (7, "6+", "", "Pin small sticky notes on a board and share them with other users."),
"Vote": (7, "7+", "", "Create a poll (yes/no, rating, multiple choice, text, images) and let others vote in real time."),
"Get Things Done": (7, "7+", "", "A simple to-do list."),
"Pomodoro": (7, "8+", "", "A timer for focused work sessions with breaks."),
"Labyrinth JS": (7, "9+", "", "Make a mind map: link ideas around a central word."),
"Curriculum": (7, "With an adult", "", "Evaluate skills (kindergarten, primary, Montessori sets) and attach pictures or media as proof."),
"Exerciser": (7, "7+", "", "Do exercises prepared by others, such as word puzzles or reordering lists (Roman numerals, vehicles)."),
"MediaViewer": (7, "4+", "A picture, video or sound in the Journal", "View a picture, video or sound from the Journal."),
}
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
acts = json.load(open(os.path.join(ROOT, 'activities.json')))
names = [a['name'] for a in acts]
assert set(D) == set(names), (set(D) ^ set(names))
assert len(D) == 61
